"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { SignUpButton } from "@clerk/nextjs";
import { ArrowRight } from "lucide-react";

const prdSections = [
  {
    id: "overview",
    label: "Overview",
    content: `{
  "productName": "TaskFlow",
  "description": "A collaborative task management app for remote teams with real-time updates and AI prioritization",
  "targetAudience": "Remote teams of 5-50 people looking for streamlined task coordination"
}`,
  },
  {
    id: "techStack",
    label: "Tech Stack",
    content: `{
  "frontend": {
    "technology": "Next.js 15 with App Router",
    "reasoning": "Best performance for real-time collaborative features"
  },
  "backend": {
    "technology": "Convex",
    "reasoning": "Real-time reactivity and TypeScript-first design"
  },
  "auth": {
    "technology": "Clerk",
    "reasoning": "Drop-in components with team management support"
  }
}`,
  },
  {
    id: "features",
    label: "MVP Features",
    content: `[
  {
    "name": "Real-time Task Board",
    "priority": "must-have",
    "description": "Kanban board with live updates across all team members"
  },
  {
    "name": "AI Task Prioritization",
    "priority": "must-have",
    "description": "Automatic priority suggestions based on deadlines and dependencies"
  },
  {
    "name": "Team Workspaces",
    "priority": "must-have",
    "description": "Isolated spaces for different projects or departments"
  }
]`,
  },
  {
    id: "architecture",
    label: "Architecture",
    content: `{
  "dataModels": ["User", "Workspace", "Task", "Comment", "Activity"],
  "apiStructure": "Convex functions with real-time subscriptions",
  "integrations": [
    "Slack notifications",
    "GitHub issue sync",
    "Calendar integration"
  ]
}`,
  },
];

export function PRDPreviewSection() {
  const [activeTab, setActiveTab] = useState("overview");

  const activeContent = prdSections.find((s) => s.id === activeTab)?.content || "";

  return (
    <section id="prd-preview" className="py-20 bg-muted/30">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto">
          {/* Section header */}
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              See what you&apos;ll get
            </h2>
            <p className="text-lg text-muted-foreground">
              A real example PRD generated by Just Start
            </p>
          </div>

          {/* PRD preview card */}
          <div className="rounded-lg border border-border bg-card overflow-hidden">
            {/* Tabs */}
            <div className="flex border-b border-border overflow-x-auto">
              {prdSections.map((section) => (
                <button
                  key={section.id}
                  onClick={() => setActiveTab(section.id)}
                  className={`px-4 py-3 text-sm font-medium whitespace-nowrap transition-colors ${
                    activeTab === section.id
                      ? "text-primary border-b-2 border-primary bg-muted/50"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  {section.label}
                </button>
              ))}
            </div>

            {/* Content */}
            <div className="p-6 bg-background/50">
              <pre className="text-sm overflow-x-auto font-mono text-muted-foreground">
                <code>{activeContent}</code>
              </pre>
            </div>
          </div>

          {/* CTA */}
          <div className="text-center mt-8">
            <SignUpButton mode="modal">
              <Button size="lg">
                Create yours now
                <ArrowRight className="h-4 w-4 ml-2" />
              </Button>
            </SignUpButton>
          </div>
        </div>
      </div>
    </section>
  );
}
